# Generated by Django 4.2.6 on 2023-10-22 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribe',
            name='user',
        ),
        migrations.AddField(
            model_name='subscribe',
            name='email',
            field=models.EmailField(default='test', max_length=254),
            preserve_default=False,
        ),
    ]
