# Generated by Django 4.2.6 on 2023-10-28 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gameapp', '0002_remove_subscribe_user_subscribe_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeroffer',
            name='game_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gameapp.game'),
            preserve_default=False,
        ),
    ]
