# Generated by Django 4.2.6 on 2023-10-28 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameapp', '0003_alter_customeroffer_game_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscribe',
        ),
    ]
