# Generated by Django 4.2.6 on 2023-11-01 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameapp', '0008_alter_game_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='summary',
            field=models.TextField(default='summary'),
            preserve_default=False,
        ),
    ]
